player1:
  type: supervised
  name: sup_5_epoch
  weight_path: output/supervised_player/checkpoints/resume_5.pth
  # tenpai_pred_weight_path: output/test_tenpai/checkpoint/resume.pth
  gpu: 0

player2:
  type: supervised
  name: sup_10_epoch
  weight_path: output/supervised_player/checkpoints/resume_10.pth
  # tenpai_pred_weight_path: output/test_tenpai/checkpoint/resume.pth
  gpu: 0

player3:
  type: supervised
  name: sup_15_epoch
  weight_path: output/supervised_player/checkpoints/resume_15.pth
  gpu: 1

player4:
  type: supervised
  name: sup_20_epoch
  weight_path: output/supervised_player/checkpoints/resume_20.pth
  gpu: 1
