player1:
  type: supervised
  name: sup1
  weight_path: output/test_fixed/checkpoint/resume.pth
  tenpai_pred_weight_path: output/test_tenpai/checkpoint/resume.pth
  gpu: 1

player2:
  type: supervised
  name: sup2
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 1

player3:
  type: supervised
  name: sup3
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 2

player4:
  type: supervised
  name: sup4
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 3