# actor_network:
#   type: MahjongPlayer

value_network:
  type: QNetwork

agent: 
  type: RLMahjong

runtime:
  seed: 42
  output_dir: ./
  checkpoint_dir: ./
  debug: False

player1:
  type: supervised
  name: player1
  weight_path: ./resume.pth
  # tenpai_pred_weight_path: output/test_tenpai/checkpoint/resume.pth
  gpu: 0

player2:
  type: supervised
  name: player2
  weight_path: ./resume.pth
  # tenpai_pred_weight_path: output/test_tenpai/checkpoint/resume.pth
  gpu: 0

player3:
  type: supervised
  name: palyer3
  weight_path: ./resume.pth
  gpu: 0

player4:
  type: supervised
  name: player4
  weight_path: ./resume.pth
  gpu: 0
