data:
  type: supervised
  root_dir: /Data/yansen/mahjong/supervised_dqa

network:
  type: MahjongPlayer

model: 
  type: SupervisedMahjong
  batch_size: 2048
  save_interval: 10000
  num_worker: 0

runtime:
  seed: 32000
  output_dir: "./output/test_fixed"
  checkpoint_dir: "./output/test_fixed/checkpoint"
  tb_log_dir: "./output/test_fixed/tb_log"
  debug: False
