data:
  type: supervised
  root_dir: /data/yansen/mahjong/supervised_v2/

network:
  type: MahjongPlayer

model: 
  type: SupervisedMahjong
  batch_size: 4096
  save_interval: 10000
  num_worker: 0

runtime:
  seed: 32000
  output_dir: "./output/supervised_player"
  debug: False
