data:
  type: tenpai
  root_dir: /data/yansen/mahjong/supervised_v2/

network:
  type: TenpaiPred

model: 
  type: SupervisedMahjong
  task: binary
  batch_size: 2048
  save_interval: 10000
  num_worker: 0

runtime:
  seed: 32000
  output_dir: "./output/test_tenpai"
  debug: False
  gpu: 1
