player1:
  type: supervised
  name: sup1
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 1

player2:
  type: supervised
  name: sup2
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 

player3:
  type: supervised
  name: sup3
  weight_path: output/test_fixed/checkpoint/resume.pth
  gpu: 1

player4:
  type: human
  name: mss